services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
    - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    build: ./api
    container_name: api
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./api:/api         
    working_dir: /api
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"

  web:
    build: ./client
    container_name: web
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./client:/client
      - /client/node_modules
    working_dir: /client
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true  

volumes:
  postgres_data:
  pgadmin_data:
